# Generated by Django 5.2.7 on 2025-12-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='enable_try_on',
            field=models.BooleanField(default=False),
        ),
    ]
