# Generated by Django 5.2.7 on 2026-02-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('yellow', 'Yellow'), ('white', 'White'), ('rose', 'Rose'), ('black', 'Black')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='metal',
            field=models.CharField(blank=True, choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='necklace_style',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='stone',
            field=models.CharField(blank=True, choices=[('diamond', 'Diamond'), ('ruby', 'Ruby'), ('emerald', 'Emerald'), ('none', 'No Stone')], db_index=True, max_length=20),
        ),
    ]
