# Generated by Django 5.2.7 on 2026-02-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_brand_product_color_product_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='ring_size_required',
            field=models.BooleanField(default=False),
        ),
    ]
