# Generated by Django 5.2.7 on 2026-02-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productimage_ring_size_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='ring_size_required',
        ),
        migrations.AddField(
            model_name='product',
            name='ring_size_required',
            field=models.BooleanField(default=False),
        ),
    ]
